'use strict';
const width = 7;
const height = 4;
const area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
const bill = 11;
const payment = 20;
const change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 8;
const midterm = 4;
const final = 3;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Karina';
const lastName = 'Kim';
let fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 13;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 505;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
const motto = (fullName += ' is the GOAT');
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
